### ISSUE TITLE
checks.core.deployed_version doesn't work against mozilla/normandy

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/poucave#139]
The reason is because https://api.github.com/repos/mozilla/normandy/releases returns `[]`, an empty array.  This is because the [documentation](https://developer.github.com/v3/repos/releases/) say: 

> This returns a list of releases, which does not include regular Git tags that have not been associated with a release. To get a list of Git tags, use the Repository Tags API.

I suppose this means several things: 

1. Standardize on the way we do releases ...
2. Change the check to pull tags instead of releases
3. ??

**Comment by leplatrem** [comment]
Good catch! The Web UI of the releases page on Github can let us believe the opposite 

Unless I'm not awake enough, I could not find any changelog on the mozilla/normandy repo. It could be an opportunity to start having one in order to be able to use the check :) 

That being said, I would also agree to use tags instead of releases ;)

**Comment by leplatrem** [comment]
Interesting... 

https://api.github.com/repos/mozilla/normandy/tags  does not return the latest tag that we can see here https://github.com/mozilla/normandy/tags (ie. `v1.127.0`)

**Comment by mythmon** [comment]
Github's API exposes pagination in the HTTP headers (docs
<https://developer.github.com/v3/guides/traversing-with-pagination/>). The
new tags are all of the form `1.x.y`, which sorts after most of the
previous Normandy releases. v1.127.0 is on page 5
<https://api.github.com/repositories/48456638/tags?page=5>.

**Comment by mythmon** [comment]
Github's API exposes pagination in the HTTP headers ([docs](https://developer.github.com/v3/guides/traversing-with-pagination/)). The
new tags are all of the form `1.x.y`, which sorts after most of the
previous Normandy releases. v1.127.0 is on [page 5](https://api.github.com/repositories/48456638/tags?page=5).

**Comment by leplatrem** [comment]
Thanks @mythmon ! Then, I will check if can sort by pushed date desc :)

**Comment by leplatrem** [comment]
The conclusion may be that we should stick to Github releases... See Fix #106
