### ISSUE TITLE
Show delta in remotesettings/push-timestamp 

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/poucave#169]
This is really for humans.  In the response can we show a delta of the timestamps so we can see how much difference there is? 

Does this even matter?  Do we only care that they are different?

**Comment by leplatrem** [comment]
In theory they should be in sync always (it's not like there should be a lag or something), but we can add the ISO datetime version of the timestamps you're right.

Note: bug is followed here https://bugzilla.mozilla.org/show_bug.cgi?id=1585042
