### ISSUE TITLE
Should error rate take up_to_date into account?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/poucave#190]
With the following situation:

```
{
  "collections": {
    "main/public-suffix-list": {
      "error_rate": 18.98,
      "statuses": {
        "up_to_date": 6004,
        "success": 2218,
        "apply_error": 1924,
        "sign_error": 14,
        "sync_error": 5
      },
      "ignored": {
        "network_error": 74
      }
    }
  },
  "min_timestamp": "2019-11-11T08:03:04.877",
  "max_timestamp": "2019-11-11T13:58:22.710"
}
```

The clients that were up-to-date obviously had no issue. What we see here is that there were approximately as many clients that received the update successfully as those who had issues applying the changes.

Shouldn't be the error rate close to 50%?

**Comment by glasserc** [comment]
Yes, I think that makes sense!

**Comment by leplatrem** [comment]
I modified the query so that it doesn't return `up_to_date` at all
