### ISSUE TITLE
Add a check for normandy-client failing to communicate with classify client

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/poucave#222]
We have [bugs like this](https://bugzilla.mozilla.org/show_bug.cgi?id=1594954) where we see mass unenrollments when the classify-client service is unavailable.  This is bad and messes up experiment date.   It's seems to be caused by the decision:  ["filter expressions will gracefully fail"](https://searchfox.org/mozilla-central/source/toolkit/components/normandy/lib/RecipeRunner.jsm#284-291). 

There will be a longer term fix.  Likely resulting in a chance in behavior on the client side.  

Poucave should monitor for event telemetry for errors talking to classify-client.  When the error rate exceeds a threshold the check should fail.

**Comment by leplatrem** [comment]
> We have bugs like this where we see mass unenrollments when the classify-client service is unavailable. 

Shall we monitor the endpoint as well? Poucave can do it but I assume this should be monitored by OPs at a high frequency as well... 

> Poucave should monitor for event telemetry for errors talking to classify-client. When the error rate exceeds a threshold the check should fail.

How are these errors reported?

**Comment by mythmon** [comment]
The code that actually deals with this is [here](https://searchfox.org/mozilla-central/source/toolkit/components/normandy/lib/RecipeRunner.jsm#488-498).

> Shall we monitor the endpoint as well? Poucave can do it but I assume this should be monitored by OPs at a high frequency as well...

Ops does indeed have monitoring for this, and in all known cases were the first to respond.

>> Poucave should monitor for event telemetry for errors talking to classify-client. When the error rate exceeds a threshold the check should fail.
>
> How are these errors reported?

These are reported as uptake telemetry, as status `CONTENT_ERROR`.
