### ISSUE TITLE
Make it possible to EXCLUDE some checks from the project level check

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/poucave#277]
In #149 (fixed in #164) it is possible to check a project with a single endpoint.  It might be nice to able to exclude some project checks from the endpoint.  

Use case: Some projects have a `deployed-version` check.  This check causes noise when we monitor with pingdom.

**Comment by leplatrem** [comment]
Then maybe we can put the *deployed version* check under a different project (eg. `deployments`)
