### ISSUE TITLE
Add minimum total in percentiles checks

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/poucave#342]
In age and duration checks, we read the Nth percentiles and compare them to some reference values.

As Ethan highlighted, we should not rely on percentiles if the total number of received events is too low.
For example, when very few «broadcast» events are received, the 75th percentile probably represents a couple of random clients, which makes the check super unstable.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1614716

**Comment by leplatrem** [comment]
@glasserc what do you think of something like this:

```sql
WITH event_uptake_telemetry AS (
    SELECT
      timestamp AS submission_timestamp,
      -- Periods of 10min
      UNIX_SECONDS(timestamp) - MOD(UNIX_SECONDS(timestamp), 600) AS period,
      SAFE_CAST(udf.get_key(event_map_values, "age") AS INT64) AS age
    FROM
        `moz-fx-data-shared-prod.telemetry_derived.events_live`
    WHERE
      timestamp > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR)
      --AND sample_id=42
      -- 99% of broadcasts that took more than 10min where Firefox 67
      AND SPLIT(app_version, '.')[OFFSET(0)] != '67'
      AND event_category = 'uptake.remotecontent.result'
      AND event_object = 'remotesettings'
      AND event_string_value = 'success'
      AND udf.get_key(event_map_values, "source") = 'settings-changes-monitoring'
      AND udf.get_key(event_map_values, "trigger") = 'broadcast'
),
total_count_by_period AS (
    SELECT period, COUNT(*) AS total
    FROM event_uptake_telemetry
    GROUP BY period
)
SELECT
    MIN(submission_timestamp) AS min_timestamp,
    MAX(submission_timestamp) AS max_timestamp,
    APPROX_QUANTILES(age, 100) AS age_percentiles,
FROM event_uptake_telemetry AS et, total_count_by_period AS tc
WHERE et.period = tc.period
  -- We get 10K-50K on periods where changes are published.
  -- This removes noise of disconnections. See https://bugzilla.mozilla.org/show_bug.cgi?id=1614716
  AND total > 5000

```

**Comment by glasserc** [comment]
I'm OK with it. We could also do the filtering on the poucave side, although I don't really see any benefit to doing it either way. I guess we handle "missing" periods OK, because we're only looking for extremely bad ones?

**Comment by leplatrem** [comment]
> We could also do the filtering on the poucave side

That obliges us to filter, agregate and compute the percentiles on the Python side... So I prefer this I think.

>  I guess we handle "missing" periods OK, because we're only looking for extremely bad ones?

Basically we exclude periods where too few clients reported broadcasts. I used 5000 arbitrarily, 1000 would also be fine.

![Screenshot from 2020-02-13 21-34-16](https://user-images.githubusercontent.com/546692/74475908-9f29a400-4ea8-11ea-8540-23c7505f3f7b.png)

But you're right, if no changes were published in the last 6H, the above query will return an empty array as percentiles, which is going to make the check fail if no safety check is added. I don't see many other alternatives :(

**Comment by glasserc** [comment]
> That obliges us to filter, agregate and compute the percentiles on the Python side... So I prefer this I think.

I was just thinking we could add `total` as a column to the output, and have the Python side skip any rows which don't have a high enough total.

> above query will return an empty array as percentiles, which is going to make the check fail if no safety check is added

From looking at the code -- it's e.g. https://github.com/mozilla-services/poucave/blob/master/checks/remotesettings/uptake_max_age.py, right? -- I think everything is safe except `min` / `max`.

**Comment by leplatrem** [comment]
> I was just thinking we could add total as a column to the output, and have the Python side skip any rows which don't have a high enough total.

Yes, but the current query returns one row. So percentiles (on agregation) are computed in Big Query.

> From looking at the code -- it's e.g. https://github.com/mozilla-services/poucave/blob/master/checks/remotesettings/uptake_max_age.py, right? -- I think everything is safe except min / max.

When no row is agregated (none has high enough total), the percentiles returns an empty array. So we'd get IndexError when looking at each Nth percentiles
