### ISSUE TITLE
Should we have the deployed version checks for Experimenter and Normandy?

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla-services/poucave#378]
I checked poucave recently and saw that the Experimenter and Normandy `deployed-version` checks were  both failing because their repos had a recent tag which was not yet depoyed to production.

In the case of Experimenter, our current release  process is to tag, deploy to stage, do a quick sanity check, then immediately deploy to production.  In practice that's usually spread over 24 hours, so that check would be expected to be red during that time.  In addition, I am hoping to move Experimenter over to a full continuous delivery strategy and do away with tags entirely, so if we kept a check like this, I imagine it would be comparing the latest commit hash on master and the latest deployed hash on production.

In the caser of Normandy, the current release process is to tag, deploy to stage,  then file a bugzilla issue alerting QA to do a full pass against it.  When that is done, it's promoted to production, but that process typically takes a full week, so that check would be red that entire time, and since we do this every two weeks I imagine it would be red basically 50% of the time in week long chunks.

Those being the case, is having these specific checks helpful for determining the overall health of the delivery platform?  Should we get rid of these entirely?  Alternatively should we demote them to something more like a warning than an error?  

I don't have a strong opinion about any of these cases, I think that's more dependent on how we want to think about what is considered  a healthy state for the  system, but it does seem to me that  marking them red and indicating that the system is unhealthy for cases that are expected, normal, and do  not directly indicate that there is a failure might be confusing or sending the  wrong signal?

**Comment by leplatrem** [comment]
We don't have the notion of «warning» state. I thought about this and decided to go with failure/success.

The global status and the «unhealthy» wording was introduced in the new UI, before we would only see a red dot on the deployed-version checks. These particular checks weren't monitored by Pingdom, so the failure in that case was more informative than anything else.

Now, with what you describe, I guess we can get rid of the checks for prod, but leave them for stage.

**Comment by leplatrem** [comment]
Will happen in https://github.com/mozilla-services/cloudops-infra/pull/2010
