### ISSUE TITLE
Add links to failing checks to the  top of the page

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla-services/poucave#379]
Looking at the current landing page of Poucave, it strikes me that it would be helpful to add some more info here:

<img width="540" alt="Screenshot 2020-03-06 17 12 19" src="https://user-images.githubusercontent.com/119884/76126670-b8b49c00-5fcd-11ea-80a8-f7d62aa2d4da.png">

that said something like

Failures: 2
Normandy: deployed-version
Normandy-Uptake-Beta: recipes-error-rate

that then link to each of the failing checks, so you could quickly see what's happening right at the top of the page.

**Comment by leplatrem** [comment]
Thanks!

Yes, exactly. We thought of doing something like when thinking about #371. Let's keep this issue, it's more explicit ;)
