### ISSUE TITLE
Split sentry projects into one for code and one for checks

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla-services/poucave#380]
The `poucave-prod` project in sentry collects both code failures in the production instance of poucave as well as the checks that have failed, and using sentry to store the failed checks is a super clever way to get alerting and graphing for those checks and I love it, but perhaps it would be cleaner to separate those into two separate sentry projects so that we don't conflate one kind of failure with the other?

**Comment by leplatrem** [comment]
Yes it would make sense. 

I would also reconsider the idea of using Sentry for checks failures and recoveries... I think Pingdom would do a better job for alerting. Sentry keeps a history whereas Pingdom only keeps the latest fail, though.

**Comment by jaredlockhart** [comment]
@leplatrem I  really like the idea of using Sentry to track the failures, yeah it gives you alerting and history, both of which I like.  I'd like to see which kinds of failures happen at different frequencies over time.  Also I realized with sentry we can add the sentry/slack bot to notify of failures in #delivery-notifications.

**Comment by leplatrem** [comment]
From what I could see in the docs and [the code](https://github.com/getsentry/sentry-python/blob/d9ffe894a778e4db04bdfd3339d61977e55f48a2/sentry_sdk/hub.py#L100-L109), I don't think it's possible to send events to multiple projects.

So our filtering will happen in the notification rule (https://sentry.io/_/resources/customer-success/alert-rules/) using tag or other criterias.
