### ISSUE TITLE
New Check: Normandy Recipe Signature Verification

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla-services/poucave#395]
The normandy production heartbeat:

https://normandy.services.mozilla.com/__heartbeat__

Implements a check to validate the signatures of all active recipes:

https://github.com/mozilla/normandy/blob/7b912b64c5319cc82500acac58ffcd9829dda788/normandy/recipes/checks.py#L46-L77

https://github.com/mozilla/normandy/blob/7b912b64c5319cc82500acac58ffcd9829dda788/normandy/recipes/signing.py

This has served us well for debugging production Normandy issues, but perhaps poucave is a better home for this kind of semantic health analysis now?

**Comment by leplatrem** [comment]
We have a check that verifies the signature of all published recipes on Remote Settings (which is the source of truth for clients).
https://delivery-checks.prod.mozaws.net/checks/normandy/recipes-signatures

What difference would there with the Normandy heartbeat? Initially our idea was to keep poucave for cross-system checks, and leave «internal» checks in each heartbeats, but if you have a differnet vision we can move lines :)

**Comment by mostlygeek** [comment]
We enhanced signature certificate checks in #767.  I believe we can close this issue now?

**Comment by jaredlockhart** [comment]
@mostlygeek @leplatrem Yes exactly that sounds perfect thank you, closing this!
