### ISSUE TITLE
See if there's a better way to query BigQuery

### ISSUE THREAD

**Issue by glasserc** [mozilla-services/poucave#60]
In #45, we introduced Redash to manage the query and as the API to access data generally. Doing so has some problems, as noted there: the code for this service is partially managed in another service (without review), and under a specific user's account, which can lead to odd situations if that user leaves the team or the company. This issue is to see if there's a clever alternative to getting data out of Bigquery.

**Comment by leplatrem** [comment]
One of the advantages of Redash is the ability to schedule the execution of the query and fetch the results instantaneously

**Comment by leplatrem** [comment]
Apparently this is the way to go :)
