### ISSUE TITLE
Check that Normandy recipes reported in uptake are all on-going

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/poucave#66]
As suggested by Ethan https://github.com/mozilla-services/poucave/pull/65#discussion_r326215996

**Comment by leplatrem** [comment]
If we would add this check today, it would error, because the following recipes were still reported by clients in the last 6H:
```
[517, 518, 530, 532, 542, 576, 597, 617, 636, 637, 651, 662, 666, 667, 668, 669, 670, 674, 677, 678, 680, 682, 683, 684, 686, 687, 688, 692, 695, 696, 698, 709, 713, 714, 715, 716, 717, 718, 722, 723, 725, 726, 729, 730, 731, 733, 734, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 747, 748, 749, 750, 751, 752, 754, 755, 756, 757, 758, 759, 760, 761, 763, 765, 768, 769, 770, 772, 773, 775, 776, 777, 778, 779, 780, 781, 782, 784, 785, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 802, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 823, 826, 827, 828, 829, 830, 831, 833, 836, 837, 841, 842, 336, 372, 373, 450, 451, 452, 453, 454, 455, 456, 483, 501]
```

I ran a [quick custom query](https://sql.telemetry.mozilla.org/queries/65094/source) to investigate the last 24H, and it looks like the same set of queries is reported by a lot of clients.

A lot of them report `content_error`, which means the JEXL filter is broken. 

Most of them report `backoff` (or the equivalent `custom_2_error` in older versions), and they shouldn't because they're not supposed to have those recipes in their local DB. 

But some clients reported `success`! Most of them are Firefox 67, mainly on recipes `576` (disabled Jul 2019), `532` (disabled May 2019), and `763` (disabled May 2019). 

I believe we can ignore the lines where only a few clients (<5) reported success, they could have had synchronization errors... (or broken IndexedDB?). Since we receive a sample of clients (1%), this could be worth investigating though. 

I would be interested to know more about this Normandy situation, especially if Remote Settings is responsible of the sync/storage failures.

Let me know what do you think!

--> Count by recipe, version, status: 
[Investigation_Normandy_Extra_Recipes_2019_09_30.csv.txt](https://github.com/mozilla-services/poucave/files/3669507/Investigation_Normandy_Extra_Recipes_2019_09_30.csv.txt)

--> 
[Investigation_Normandy_Extra_Recipes_2019_09_30-by-version.csv.txt](https://github.com/mozilla-services/poucave/files/3669528/Investigation_Normandy_Extra_Recipes_2019_09_30-by-version.csv.txt)

/cc @mythmon

**Comment by mythmon** [comment]
First, my usual response is that we know from our history with Normandy that changes to recipes that we publish will stick around for a very long time, even after we unpublish them. There has been one main hypothesis that we've come up with over time, but we've never really dug into it. It is that some things between Normandy Server and Normandy Client caches the data for an inappropriately long amount of time, and so we get stale recipe data. This could include caching middle boxes by ISPs or in enterprises, faulty client caches, or malicious actors (though the last is not very likely).

RS gives us another complication that users may have stale data in their RS database. Consider this chain of events:

* User runs Firefox
* Remote Settings syncs a set of recipes
* User closes Firefox and goes on vacation for a month
* User returns and starts Firefox
* Normandy runs immediately and executes stale recipes
* Remote Settings updates the recipe collection, causing Normandy to run again

In this case, we could see recipes from as far back as the first Remote Settings enabled Normandy. Perhaps to combat this we could add a check to make sure the data is sufficiently fresh before executing it.

On the other hand, it seems like there is a lot more stale recipe execution than I'm used to seeing. Thousands a day seems high, though maybe it isn't. I usually am happy to wave away a 1% or lower "weirdness" rate when it comes to Telemetry, but this seems higher than that.

Maybe this can be solely explained by the Remote Settings integration, and the staleness check I mentioned above could help. @leplatrem: Have you seen any recipes that were disabled before Remote Settings integration was completed that show up in the data today?
