### ISSUE TITLE
Clicking refresh breaks the graph

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/poucave#710]
When clicking the REFRESH button on a check it breaks the graph. 

![image](https://user-images.githubusercontent.com/83972/102524823-586b8400-404e-11eb-82d2-c17c3ee9e48f.png)

**Comment by leplatrem** [comment]
Cannot reproduce with latest UI

**Comment by mostlygeek** [comment]
the latest UI is not deployed to prod yet?  The cause of the error is a 400, invalid refresh secret.

**Comment by leplatrem** [comment]
> the latest UI is not deployed to prod yet? The cause of the error is a 400, invalid refresh secret.

It is. But invalid refresh secret is something else.

You can find the secret value here:
https://github.com/mozilla-services/cloudops-infra/blob/336fc5f45bb8a2408a5bb98ffb61a35799c6b77f/projects/poucave/k8s/values/app.yaml#L15
You can clear cache/localstorage and refresh again, it will prompt for a value.

Also, forcing refresh is not specifically recommended, unless there's a good reason (eg. you're sure the problem fixed upstream and want to refresh check status)

**Comment by mostlygeek** [comment]
Thanks that worked! 

Flushed all local data (cookies, local storage, etc).  Hitting refresh then prompted me for the new secret.  Entered it and it works now.
