### ISSUE TITLE
Ask for new secret on 400 response from server

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/poucave#740]
The web UI should prompt for a new secret on HTTP 400 (forbidden) to a manual refresh request.  The current fix is to manually clear local data (#710).

**Comment by leplatrem** [comment]
I could not really reproduce, this should already be the case: 

https://github.com/mozilla-services/poucave/blob/3c1393285b17cebbba5200b96cf0b22de18a9030/poucave/html/js/app/components/Dashboard.mjs#L150-L153
