### ISSUE TITLE
New check for Content Signature certificate chain

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/poucave#767]
Normandy has [a check](https://github.com/mozilla/normandy/blob/dc24516f34d2d9d2920fcb62683b1fe3eca1fda3/normandy/recipes/checks.py#L125-L164) that checks the content signature certificates do not expire soon. 

Duplicating, and expanding this for Poucave would be useful.  It should check Remote Settings content signatures for: 

- signatures are valid 
- certificate chain is valid 
- certificate have at least `x` hours before they expire
- any others?

**Comment by leplatrem** [comment]
Our existing check only verifies the leaf certificate of the chain.

Even though it should not be possible to generate a leaf certificate that expires after its parent, it does not hurt to include the whole chain in the verification...

**Comment by mostlygeek** [comment]
I had a conversation with @mythmon about this.  Here's how Normandy does it: 

* [the heartbeat check](https://github.com/mozilla/normandy/blame/master/normandy/recipes/checks.py#L126) 
* [the function to check the whole change](https://github.com/mozilla/normandy/blob/dc24516f34d2d9d2920fcb62683b1fe3eca1fda3/normandy/recipes/signing.py#L186)
  *  maybe we can extract and put this into shared library that can be imported into poucave?

**Comment by leplatrem** [comment]
We have a library already, https://github.com/mozilla-services/python-autograph-utils/blob/0090df0f2da2b9412d78f42b3af0e5f88572d12d/autograph_utils/__init__.py#L339-L343
