### ISSUE TITLE
[taskcluster] Create a check that test a task end to end

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/poucave#838]
- Define specific index string (eg. `"check.task.e2e"`)
- Query index to obtain task ID
- If no task, create a new task, specifying index route 
- If task has completed, then download artifact, and create a new task
- If task has pending state, and is less than X minutes old, then do nothing

This check verifies that:
- task can be created
- index is listening to `index.*` topics on pulse
- artifacts are published on store

**Comment by leplatrem** [comment]
We decided to split this into individual checks instead
