### ISSUE TITLE
[taskcluster] Add check for hooks

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/poucave#851]
If it doesn't exist yet, create a hook that:
- creates a task every X minutes that publishes an artifact, and creates a second task, and makes it dependent on itself, so that 
- creates an other task that depends on the previous task completion or fails

The check will verifies that the second task is always successful.

The first task can only create another task ("decision" tasks) as long as the task has the required scopes

**Comment by jwhitlock** [comment]
Maybe related to https://github.com/taskcluster/taskcluster/issues/1243

**Comment by jwhitlock** [comment]
After some research, I think an intermediate milestone would be:

* A check that looks in the index for the latest run of a hook that runs every 5 minutes, and verifies that it was scheduled in the last 6 minutes.
* A check that verifies that hook exists, and if not, creates it.

The intermediate milestone would allow us to get the basic Telescope workflow in place, then expand to a decision task later.

A decision task using [taskgraph](https://hg.mozilla.org/ci/taskgraph) requires some additional infrastructure:

* A repository with the task graph definitions, like [taskcluster/ci](https://github.com/taskcluster/taskcluster/tree/main/taskcluster/ci)
* An execution environment like [mozillareleases/taskgraph](https://hub.docker.com/r/mozillareleases/taskgraph) to:
  1. setup the environment for `taskgraph`
  2. download and install `taskgraph`
  3. download the task definitions
  3. run `taskgraph decision` to create the tasks
  
See Taskcluster's [.taskcluster.yml](https://github.com/taskcluster/taskcluster/blob/main/.taskcluster.yml#L116-L176) for a taste of what that looks like.

**Comment by jwhitlock** [comment]
I manually created a [periodic hook](https://community-tc.services.mozilla.com/hooks/project-taskcluster/poucave-issue-851-test). It required a [role](https://community-tc.services.mozilla.com/auth/roles/hook-id%3Aproject-taskcluster%2F*) as well. It runs every 15 minutes, and updates an [index entry](https://community-tc.services.mozilla.com/tasks/index/project.taskcluster.telescope.poucave-issue-851-test/07), which includes an [artifact](https://community.taskcluster-artifacts.net/CpdXxT8UQoe3htcLWj7Z8g/0/public/results/status.json).

Next, to create the Telescope checks and pick non-temporary names.

**Comment by jwhitlock** [comment]
@leplatrem I'd appreciate it if you could look at turning this into a Telescope task. I've spent my time looking at Taskcluster, I haven't spent much time learning Telescope yet.

**Comment by leplatrem** [comment]
The check implemented in #871 will be enough to achieve this.
We closed #872 because the hook definition is very likely to live elsewhere.
