### ISSUE TITLE
Deploy minimalist Telescope instance

### ISSUE THREAD

**Issue by petemoore** [mozilla-services/poucave#860]
https://bugzilla.mozilla.org/show_bug.cgi?id=1722921

**Comment by jwhitlock** [comment]
@cvallas was assigned to [bug 1722921](https://bugzilla.mozilla.org/show_bug.cgi?id=1722921) 13 days ago.

@bsieber-mozilla forked the project to https://github.com/mozilla-it/poucave, and deployed it to GCP using an existing GCP account and processes. I believe he used the Poucave configuration from https://github.com/taskcluster/taskcluster/pull/4941.

@bsieber-mozilla any details I got wrong or missed?

**Comment by bsieber-mozilla** [comment]
## Repo

https://github.com/mozilla-it/telescope-demo

## Stage Deployment

https://telescope-demo.api.data.allizom.org/html/index.html

## Provisioned and Invited Members for Access

![Screen Shot 2021-08-11 at 3 23 18 PM](https://user-images.githubusercontent.com/53873986/129111499-ad614652-c654-4dd4-b329-782b77b79189.png)

**Comment by bsieber-mozilla** [comment]
Currently deployed to staging. It will re-deploy on Pull Request merges onto `main`

**Comment by bsieber-mozilla** [comment]
-[ ] SVG added to deploy
-[ ] SRE-deployed/maintained OPs

**Comment by bsieber-mozilla** [comment]
I believe that last check-box would be for a later time, as what we have now should be efficient.

**Comment by petemoore** [comment]
Agreed, thanks @bsieber-mozilla !
